# paths and folder names

PATH_FROM_ROOT_TO_PY_GENERATOR = "webPage/generator/"
PATH_FROM_GENERATOR_TO_UNIT_TESTS = "unitTests/"
PATH_FROM_ROOT_TO_UNIT_TESTS = PATH_FROM_ROOT_TO_PY_GENERATOR + PATH_FROM_GENERATOR_TO_UNIT_TESTS
PATH_FROM_ROOT_TO_UT4UT = PATH_FROM_ROOT_TO_PY_GENERATOR + "unitTests4unitTests/"
UT_TEMP1_FOLDER_NAME = "temp1"
UT_TEMP2_FOLDER_NAME = "temp2"
